//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAL_PlayAndLearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestion
    {
        public int ID { get; set; }
        public string QuestionText { get; set; }
        public string AnswerOne { get; set; }
        public string AnswerTwo { get; set; }
        public string AnswerThree { get; set; }
        public string AnswerFour { get; set; }
        public int CorrectAnswer { get; set; }
        public int Points { get; set; }
        public int ITTestID { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
