//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAL_PlayAndLearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistration
    {
        public UserRegistration()
        {
            this.UserGameInformations = new HashSet<UserGameInformation>();
            this.UserPersonalInformations = new HashSet<UserPersonalInformation>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserEMail { get; set; }
    
        public virtual ICollection<UserGameInformation> UserGameInformations { get; set; }
        public virtual ICollection<UserPersonalInformation> UserPersonalInformations { get; set; }
    }
}
