//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAL_PlayAndLearn
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPersonalInformation
    {
        public int ID { get; set; }
        public string YearsOld { get; set; }
        public string CityName { get; set; }
        public string SchoolName { get; set; }
        public string Sex { get; set; }
        public string Class { get; set; }
        public string AvatarPicture { get; set; }
        public int UserRegID { get; set; }
    
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
